[mysqldb]
host  = "127.0.0.1"
user = "root"
port = 3306
database = "starwarsDB"
password = "harsh_root"


[swapi]
home_url = "https://swapi.py4e.com"
vehicle = "/api/vehicles"
starship = "/api/starships"
film = "/api/films"

